# Site settings
title: adamaoc

description: > # this means to ignore newlines until "baseurl:"
  I'm a front-end developer working on awesome web applications using Ember and a whole host of cool technologies.
  I write automotive reviews at txGarage.com and love all things automotive and tech.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adamaoc
github_username:  adamaoc

# Build settings
markdown: kramdown


# Section text
work_text: "I work for a Dallas based company called Dialexa where we build custom web applications..."
txg_text: "...I write automotive reviews and news at txGarage.com..."
instagram_text: "...I share photos of cars, family, and tech on my Instagram..."
twitter_text: "...I talk about all kinds of nonsense on Twitter..."
codepen_text: "...I make front-end stuff on Codepen.io..."
codepen_blog_text: "...and also blog on Codepen Blog..."
amp_text: "...I work on some independent projects via ampnetmedia.com..."
